spring.application.name=Pop_Archive
spring.security.user.name=admin
spring.security.user.password=admin123


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true


logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG